apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  releaseName: portainer
  chart:
    spec:
      chart: portainer
      version: 1.0.65       # example
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: portainer 
  values:
    service:
      type: ClusterIP
      port: 9000

    ingress:
      enabled: true
      ingressClassName: "traefik"
      hosts:
        - host: portainer.demo.local 
          paths:
            - path: /
              pathType: Prefix

    persistence:
      enabled: true
      size: 5Gi
