apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: flux-system
spec:
  interval: 5m
  releaseName: portainer

  chart:
    spec:
      chart: portainer
      version: 1.0.65
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system   
  # Where the chart will actually be installed
  targetNamespace: portainer

  install:
    createNamespace: true

  upgrade:
    remediation:
      retries: 3

  values:
    service:
      type: ClusterIP
      port: 9000
    persistence:
      enabled: true
      size: 5Gi
