apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.90.9      
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  targetNamespace: tailscale
  install:
    createNamespace: true
  values:
    oauth:
      clientId: "kkWGGgruR421CNTRL"
      clientSecret: "tskey-client-kkWGGgruR421CNTRL-HLGXN2FThLSwusaXm2YfLSxZeMidbmurP"
